version: '3.8'

services:
  db:
    image: postgres:15.10-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  db_manager:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - db_manager
    environment:
      SPRING_DATASOURCE_URL_LOCAL: ${SPRING_DATASOURCE_URL_LOCAL}
      SPRING_DATASOURCE_URL_DEV: ${SPRING_DATASOURCE_URL_DEV}
      SPRING_DATASOURCE_URL_PROD: ${SPRING_DATASOURCE_URL_PROD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge